### ISSUE TITLE
Landmarks on 3D model after scanning.

### ISSUE THREAD

**Issue by MorozPavlo** [StandardCyborg/StandardCyborgSDK#13]
As I understand, the current SDK lacks the necessary files or models for 3D point detection on a 3D model. Can you please clarify how it is possible to place points on a 3D model using only 2D coordinates?

Are there any ways to obtain the missing files?

**Comment by aaptho** [comment]
There are no missing files to speak of.

The landmarking actually works on RGB frames in 2D. But you can un-project back into 3D to place the 2D landmarks on the 3D point cloud.

It’s been ages since I’ve used this, so my memory is foggy and there are no examples, and it might not even work anymore, but check out [OfflineSurfelLandmarking](https://github.com/StandardCyborg/StandardCyborgSDK/blob/f9ae74e0b06ee747c3b74fdbaba73b46d0622977/StandardCyborgFusion/Algorithm/OfflineSurfelLandmarking.hpp#L20)
